name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Reservation.sln
    - name: Build
      run: dotnet build --no-restore --configuration Release ./src/Reservation.Api
    - name: Test
      run: dotnet test -c Debug --no-restore "--logger:Console;verbosity=quiet" ./test/Reservation.Application.Tests
